/**
 * lib/ttsChunker.ts
 *
 * Sentence-aware text chunking for local Kokoro TTS.
 * Ensures that responses generated by Qwen are divided into natural,
 * spoken-length segments (preferring 200–280 characters, with a HARD CEILING of 300 chars)
 * so that local CPU/GPU Kokoro synthesis completes smoothly and never approaches the 20-second timeout.
 */

export interface ChunkOptions {
  /**
   * Maximum target character length for a single TTS chunk.
   * Default: 260 characters (hard-capped at HARD_MAX_TTS_CHUNK_LENGTH = 300).
   */
  maxChunkLength?: number;

  /**
   * Preferred minimum character length before splitting off a chunk.
   * Default: 160 characters.
   */
  minChunkLength?: number;
}

export const HARD_MAX_TTS_CHUNK_LENGTH = 100;
export const DEFAULT_TARGET_CHUNK_LENGTH = 65;
export const DEFAULT_MIN_CHUNK_LENGTH = 35;

// Common English abbreviations that shouldn't be treated as sentence ends
const COMMON_ABBREVIATIONS = new Set([
  "mr",
  "mrs",
  "ms",
  "dr",
  "prof",
  "sr",
  "jr",
  "vs",
  "etc",
  "eg",
  "ie",
  "approx",
  "appx",
  "dept",
  "est",
  "min",
  "sec",
  "no",
  "gen",
  "rep",
  "sen",
  "st",
  "ave",
  "rd",
  "blvd",
  "jan",
  "feb",
  "mar",
  "apr",
  "jun",
  "jul",
  "aug",
  "sep",
  "sept",
  "oct",
  "nov",
  "dec",
  "am",
  "pm",
  "us",
  "uk",
  "usa",
]);

/**
 * Splits text into individual sentences while respecting common abbreviations,
 * numbers with decimals, and ellipsis.
 */
export function extractSentences(text: string): string[] {
  const trimmed = text?.trim();
  if (!trimmed) return [];

  const sentences: string[] = [];
  let currentStart = 0;

  for (let i = 0; i < trimmed.length; i++) {
    const char = trimmed[i];

    if (char === "." || char === "?" || char === "!") {
      // Check if next character indicates sentence boundary
      const isEnd = i === trimmed.length - 1;
      const nextChar = isEnd ? "" : trimmed[i + 1];
      const isWhitespaceNext = isEnd || /\s/.test(nextChar);

      if (isWhitespaceNext) {
        // Look back at the token preceding this punctuation
        const precedingSlice = trimmed.slice(currentStart, i);
        const lastWordMatch = precedingSlice.match(/([A-Za-z0-9]+)$/);
        const lastWord = lastWordMatch ? lastWordMatch[1].toLowerCase() : "";

        // Check if preceding token is a single letter (e.g. initial "J.") or abbreviation
        const isSingleLetter = lastWord.length === 1 && /[a-z]/i.test(lastWord);
        const isAbbrev = COMMON_ABBREVIATIONS.has(lastWord);
        const isDigitPreceding = /\d$/.test(precedingSlice);
        const isDigitNext = !isEnd && /\d/.test(trimmed[i + 1]);

        if ((isAbbrev || isSingleLetter || (isDigitPreceding && isDigitNext)) && char === ".") {
          // Skip abbreviation or decimal number
          continue;
        }

        // Check for multiple punctuation marks like "..." or "!?"
        let endPunct = i;
        while (endPunct + 1 < trimmed.length && /[.!?]/.test(trimmed[endPunct + 1])) {
          endPunct++;
        }
        i = endPunct;

        const sentence = trimmed.slice(currentStart, i + 1).trim();
        if (sentence) {
          sentences.push(sentence);
        }

        // Advance currentStart past any whitespace
        while (i + 1 < trimmed.length && /\s/.test(trimmed[i + 1])) {
          i++;
        }
        currentStart = i + 1;
      }
    }
  }

  // Trailing portion
  if (currentStart < trimmed.length) {
    const remainder = trimmed.slice(currentStart).trim();
    if (remainder) {
      sentences.push(remainder);
    }
  }

  return sentences;
}

/**
 * Safely subdivides an unusually long sentence into smaller clauses
 * at semicolons, colons, dashes, commas, or word boundaries.
 * Guarantees every returned piece is <= maxLength.
 */
export function splitLongSentence(sentence: string, maxLength: number): string[] {
  const trimmed = sentence.trim();
  if (trimmed.length <= maxLength) {
    return [trimmed];
  }

  const parts: string[] = [];
  let remaining = trimmed;

  while (remaining.length > maxLength) {
    let splitIndex = -1;

    // 1. Try splitting at clause punctuation (; : - —)
    const clauseRegex = /[;:—]| - /g;
    let match: RegExpExecArray | null;

    while ((match = clauseRegex.exec(remaining)) !== null) {
      const idx = match.index + match[0].length;
      if (idx >= 15 && idx <= maxLength) {
        splitIndex = idx;
      }
    }

    // 2. If no clause boundary, try splitting at commas (, )
    if (splitIndex === -1) {
      const commaRegex = /,\s+/g;
      while ((match = commaRegex.exec(remaining)) !== null) {
        const idx = match.index + match[0].length;
        if (idx >= 15 && idx <= maxLength) {
          splitIndex = idx;
        }
      }
    }

    // 3. If no comma, split at last space <= maxLength
    if (splitIndex === -1) {
      const lastSpace = remaining.lastIndexOf(" ", maxLength);
      if (lastSpace >= 10) {
        splitIndex = lastSpace + 1;
      }
    }

    // 4. Extreme fallback: if an individual unbroken token > maxLength, split at maxLength
    if (splitIndex === -1 || splitIndex > maxLength) {
      splitIndex = maxLength;
    }

    const chunk = remaining.slice(0, splitIndex).trim();
    if (chunk) {
      parts.push(chunk);
    }
    remaining = remaining.slice(splitIndex).trim();
  }

  if (remaining) {
    parts.push(remaining);
  }

  return parts;
}

/**
 * Splits text into sentence-aware chunks suitable for sequential TTS synthesis.
 * - Enforces HARD_MAX_TTS_CHUNK_LENGTH = 100 characters.
 * - Targets preferred ~65 character range (DEFAULT_TARGET_CHUNK_LENGTH = 65).
 * - Prioritizes sentence boundaries (. ? !), then clauses (; :), then commas, then word spaces.
 * - Never splits inside a word (unless single unbroken token exceeds 100 chars).
 * - Preserves complete text content without truncation, duplication, or reordering.
 */
export function splitTextForTTS(text: string, options: ChunkOptions = {}): string[] {
  const trimmed = text?.trim();
  if (!trimmed) return [];

  // Enforce true hard maximum of HARD_MAX_TTS_CHUNK_LENGTH (100 characters)
  const rawMax = options.maxChunkLength ?? DEFAULT_TARGET_CHUNK_LENGTH;
  const maxLen = Math.min(Math.max(rawMax, 35), HARD_MAX_TTS_CHUNK_LENGTH);
  const minLen = options.minChunkLength ?? DEFAULT_MIN_CHUNK_LENGTH;

  // Fast path: text is already within single-chunk bounds
  if (trimmed.length <= maxLen) {
    return [trimmed];
  }

  // 1. Extract natural sentences
  const rawSentences = extractSentences(trimmed);
  if (rawSentences.length === 0) {
    return splitLongSentence(trimmed, maxLen);
  }

  // 2. Ensure every individual sentence is strictly <= maxLen
  const atomicSentences: string[] = [];
  for (const s of rawSentences) {
    if (s.length > maxLen) {
      atomicSentences.push(...splitLongSentence(s, maxLen));
    } else {
      atomicSentences.push(s);
    }
  }

  // 3. Greedily assemble sentences into chunks up to maxLen
  const chunks: string[] = [];
  let currentChunk = "";

  for (const sentence of atomicSentences) {
    if (!currentChunk) {
      currentChunk = sentence;
      continue;
    }

    const potentialLen = currentChunk.length + 1 + sentence.length;

    if (potentialLen <= maxLen) {
      currentChunk += " " + sentence;
    } else {
      // Current chunk is full; push it and start a new chunk
      chunks.push(currentChunk.trim());
      currentChunk = sentence;
    }
  }

  if (currentChunk.trim()) {
    chunks.push(currentChunk.trim());
  }

  // 4. Final safety assertion pass: Guarantee NO chunk exceeds HARD_MAX_TTS_CHUNK_LENGTH (100 chars)
  const safeChunks: string[] = [];
  for (const c of chunks) {
    if (c.length <= HARD_MAX_TTS_CHUNK_LENGTH) {
      safeChunks.push(c);
    } else {
      safeChunks.push(...splitLongSentence(c, HARD_MAX_TTS_CHUNK_LENGTH));
    }
  }

  return safeChunks;
}
